name: License Header Check

on:
  pull_request:
    paths:
      - "**/*.py"
      - "!clients/**"
      - ".github/workflows/check-license.yml"
      - ".licenserc.yaml"
  push:
    branches:
      - develop
    paths:
      - "**/*.py"
      - "!clients/**"
      - ".github/workflows/check-license.yml"
      - ".licenserc.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-license-header:
    name: Check License Header
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Check license headers
        uses: apache/skywalking-eyes/header@eddd8f193e5c1739a76dad4074f50ede635a19fe
        with:
          mode: check
